language: r

r_github_packages:
    - mllg/checkmate
    - tudo-r/BatchJobs
    - jimhester/covr

before_script:
    - curl -L https://raw.githubusercontent.com/rdatsci/travis-r-tools/master/update-packages.r -o /tmp/update-packages.r
    - Rscript /tmp/update-packages.r

after_success:
    - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: always
